export default {
  KEYS: {
    BOOKING: "BOOKING",
    CONFIRMACION_VENTA: "CONFIRMACION_VENTA",
    CARGUE_EN_PLANTA: "CARGUE_EN_PLANTA",
    FACTURACION: "FACTURACION",
    INFORMACION_SANITARIA: "INFORMACION_SANITARIA",
    MANEJO_EN_PUERTO: "MANEJO_EN_PUERTO",
    INFORMACION_ADUANERA: "INFORMACION_ADUANERA",
    GIROS_CLIENTES: "GIROS_CLIENTES",
    INFORMACION_CAMBIARIA: "INFORMACION_CAMBIARIA",
    ACUERDOS_COMERCIALES: "ACUERDOS_COMERCIALES",
  },

  go(key) {
    storeValue("active_section", key);
  },

  is(key) {
    return appsmith.store.active_section === key;
  },
};